name: botim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  intl_phone_number_input: ^0.7.1
  easy_localization: ^3.0.1
  carousel_slider: ^4.1.1
  flutter_otp_text_field: ^1.1.0+2
  group_radio_button: ^1.2.0
  form_field_validator: ^1.1.0
  badges: ^2.0.3
  flutter_staggered_grid_view: ^0.6.2
  image_picker: ^0.8.6
  http: ^0.13.5
  timelines: ^0.1.0
  store_redirect: ^2.0.1
  flutter_rating_bar: ^4.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

