name: botim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  intl_phone_number_input: ^0.7.1
  flutter_otp_text_field: ^1.1.0+2
  group_radio_button: ^1.2.0
  form_field_validator: ^1.1.0
  badges: ^2.0.3
  flutter_staggered_grid_view: ^0.6.2
  timelines: ^0.1.0
  store_redirect: ^2.0.1
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  modal_progress_hud_nsn: ^0.3.0
  timezone: ^0.9.0
  open_settings: ^2.0.2
  shared_preferences: ^2.0.11
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.6
  google_sign_in: ^5.4.2
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  video_player: ^2.4.8
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    #  - images/a_dot_ham.jpeg


